version: "3.7"
services:
  grafana:
    image: unisec/grafana:latest
    container_name: unidash
    hostname: grafana
    ports: 
      - "3000:3000"
    volumes:
      - ./grafana/:/var/lib/grafana
      - ./imgs:/usr/share/grafana/public/img
      - ./scripts:/usr/share/grafana/public/build
      - ./grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-un1s3c}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLE= TRUE
    user: "root"

    